### ISSUE TITLE
Update code so it works with latest Phabricator

### ISSUE THREAD

**Issue by g-p-g** [bluehawk/phabricator-sprint#3]
Hello,

Thanks for the nice extension, I have been using it for months. Today I decided to upgrade Phabricator to the most recent version and had some severe issues with no existing tasks being accessible, after looking around I had to go back one commit before https://secure.phabricator.com/rP83db5965ab6c640864fb8b66d813369274d40594 (libphutil also had to be adjusted). It looks like this new needProjectPHIDs broken this extension, but I can't tell for sure as I haven't looked into its code so far. Do you know if that's the case and if there's any plan to update it so it works with the latest Phabricator?

**Comment by carlaustin** [comment]
FYI - there is this another one that wikimedia have been keeping up to date at https://github.com/wikimedia/phabricator-extensions-Sprint that looks like it may have originated from this one. I've just tried it and it works with the latest code.

**Comment by g-p-g** [comment]
Indeed, I saw it while going through this issue. I saw it's using a different chart too, and there are reports mentioning that the extension is making things very slow (these reports are coming from wikimedia itself). This extension here has been working fine, so I would prefer to stick to it and given the time I'll take a look into it to fix this issue if no one does it.

**Comment by carlaustin** [comment]
Cheers for the info. If I find it particularly slow I'll also look into fixing this one instead.

**Comment by g-p-g** [comment]
Hello, I came up with the following patch which causes this extension to work with the latest PH (I'll fork this later and will submit a PR, but I'm not sure if this project is active or not):

```
diff --git a/src/BurndownData.php b/src/BurndownData.php
index fcc6e41..f13e883 100644
--- a/src/BurndownData.php
+++ b/src/BurndownData.php
@@ -70,6 +70,7 @@ class BurndownData {
     $tasks = id(new ManiphestTaskQuery())
       ->setViewer($viewer)
       ->withAnyProjects(array($this->project->getPHID()))
+      ->needProjectPHIDs(true)
       ->execute();
 
     // Now load *every transaction* for those tasks. This loads all the
@@ -440,8 +441,8 @@ HERE
    */
   private function buildTasksTree() {
     // Shorter constants
-    $DEPENDS_ON = PhabricatorEdgeConfig::TYPE_TASK_DEPENDS_ON_TASK;
-    $DEPENDED_ON = PhabricatorEdgeConfig::TYPE_TASK_DEPENDED_ON_BY_TASK;
+    $DEPENDS_ON = ManiphestTaskDependsOnTaskEdgeType::EDGECONST;
+    $DEPENDED_ON = ManiphestTaskDependedOnByTaskEdgeType::EDGECONST;
 
     // Load all edges of depends and depended on tasks
     $edges = id(new PhabricatorEdgeQuery())
@@ -693,4 +694,4 @@ HERE
     return $events;
   }
 
-}
\ No newline at end of file
+}
diff --git a/src/SprintTaskStoryPointsField.php b/src/SprintTaskStoryPointsField.php
index c28cff2..c4706c7 100644
--- a/src/SprintTaskStoryPointsField.php
+++ b/src/SprintTaskStoryPointsField.php
@@ -43,17 +43,27 @@ final class SprintTaskStoryPointsField extends ManiphestCustomField
   public function showField() {
     static $show = null;
 
-    if ($show == null)
-    {
-      $toTest = $this->getObject()->getProjectPHIDs();
-      if (empty($toTest)) {
+    $viewer = $this->getViewer();
+
+    if ($show == null) {
+      $id = $this->getObject()->getID();
+      $task = id(new ManiphestTaskQuery())
+          ->setViewer($viewer)
+	  ->withIds(array($id))
+	  ->needProjectPHIDs(true)
+	  ->executeOne();
+      if (!($task instanceof ManiphestTask)) {
+        return $show = false;
+      }
+      $project_phids = $task->getProjectPHIDs();
+      if (empty($project_phids)) {
         return $show = false;
       }
       // Fetch the names from all the Projects associated with this task
       $projects = id(new PhabricatorProject())
         ->loadAllWhere(
         'phid IN (%Ls)',
-        $this->getObject()->getProjectPHIDs());
+        $project_phids);
       $names = mpull($projects, 'getName');
 
       // Set show to true if one of the Projects contains "Sprint"
```

**Comment by bluehawk** [comment]
Sorry, I've been out of town on vacation. 

Thanks for the compliments, good to hear you've been enjoying it. 

I am not actively developing this extension anymore, but I'd be more than willing to merge in your pull request when you send it. :)

**Comment by g-p-g** [comment]
Finally got to do it, closing this in favor of the pull request.
