### ISSUE TITLE
Use of GPL license incompatible with Apache 2.0 license

### ISSUE THREAD

**Issue by carlaustin** [bluehawk/phabricator-sprint#4]
Hi,

Thanks very much for your plugin, I've been playing with it for some time (I submitted a minor bug fix a while back) and it has been very useful in adding a feature that is clearly missing from Phabricator currently. I have noticed that you attached the GPL license to it and this has introduced an issue for me.

I'm building something open source that deploys Phabricator as part of a toolset, and I would very much like to include this extension, or possibly the Wikimedia one that forked from it as many development projects are sprint based, something that Phabricator doesn't properly account for.
The problem I've got is that I will be looking to use the Apache 2.0 license, the same one that Phabricator itself uses. Unfortunately the GPL license is non-compatible with the Apache 2.0 license due to the strong copyleft nature of it. 

I was wondering whether you might consider a license change, dual licensing or perhaps continuing with the GPL, however with the introduction of an open source exclusion to enable the use of the extension with other open source licenses currently incompatible but still preventing the use of it within closed source software?

Many Thanks for sharing your work with others like myself.

Carl

**Comment by carlaustin** [comment]
I don't know if you've seen this but have you had a chance to consider this request? I'm happy to discuss this further, provide more details if you are unsure or unclear.

Many Thanks

Carl

**Comment by bluehawk** [comment]
Sorry for the delay in getting back to you.  

I've changed the license to Apache 2.0.

**Comment by carlaustin** [comment]
No problem and many thanks, much appreciated!
