### ISSUE TITLE
Unhandled Exception ("PhutilMissingSymbolException")

### ISSUE THREAD

**Issue by dpaola2** [bluehawk/phabricator-sprint#7]
On latest version of phabricator (3b2fa99c57db96fe446b54ac50d271e6974265b1).

Steps to reproduce:

1. Clone phabricator-sprint repository
2. Configure phabricator configuration in phabricator/conf/local/local.json to include "load-libraries" key that points to phabricator-sprint repository
3. Run `arc liberate src` from within the phabricator-sprint repository
4. Add end date to a project containing the word "sprint"
5. Click "View Burndown"

Result:

Failed to load class or interface 'PHUIErrorView': the class or interface 'PHUIErrorView' is not defined in the library map for any loaded phutil library. If this symbol was recently added or moved, your library map may be out of date. You can rebuild the map by running 'arc liberate'. For more information, see: http://www.phabricator.com/docs/phabricator/article/libphutil_Libraries_User_Guide.html

![](https://www.dropbox.com/s/hhyygo6rg9qkdh9/Screenshot%202015-04-29%2010.48.53.png?dl=1)

**Comment by calfzhou** [comment]
+1 the same issue.

**Comment by g-p-g** [comment]
See https://secure.phabricator.com/D11867. It seems you can fix it by renaming PHUIErrorView to PHUIInfoView.
