### ISSUE TITLE
Call to undefined method ManiphestTaskQuery::withAnyProjects()

### ISSUE THREAD

**Issue by calfzhou** [bluehawk/phabricator-sprint#8]
with latest phabricator version: 4f5a0f2391d842405966d904b055ac7d9e65addf
and latest phabricator-sprint: e411edb06b604a8652b4d29d4b3334e680e1fb43

Set start & end date to a `Sprint xx` project, then click `View Burndown`, got the following exception:

```
>>> UNRECOVERABLE FATAL ERROR <<<
Call to undefined method ManiphestTaskQuery::withAnyProjects()
/opt/phacility/extensions/phabricator-sprint/src/BurndownData.php:72
┻━┻ ︵ ¯\_(ツ)_/¯ ︵ ┻━┻
```

![image](https://cloud.githubusercontent.com/assets/3761553/7467745/d4b3067a-f331-11e4-9cee-48f204ef7f8d.png)

**Comment by bluehawk** [comment]
Should be fixed by #11. Thanks @dpaola2
